apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t5gsq3wlw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t5gsq3wlw-nodejs 
  name: t5gsq3wlw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: t5gsq3wlw-nodejs 
